image:
  - Visual Studio 2019

branches:
  only:
    - master

install:
  - set PATH=C:\Qt\5.15.2\msvc2019_64\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" -D Qt5_DIR=C:\Qt\5.15.2\msvc2019_64\lib\cmake\Qt5 ..
  - cmake --build .