image:
  - Visual Studio 2019
  - Ubuntu2004

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019

    install:
      - set PATH=C:\Qt\Tools\mingw810_32\bin;%PATH%
      - set Boost_ROOT=C:\Libraries\boost_1_73_0

    build_script:
      - cmake -G "MinGW Makefiles" -D Qt5_DIR=C:\Qt\5.15.2\mingw81_32\lib\cmake\Qt5 ..
      - cmake --build .
  
  -
    matrix:
      only:
        - image: Ubuntu2004
    
    install:
      - sudo apt update
      - sudo apt install -y mesa-common-dev libglu1-mesa-dev
      - sudo apt install -y libboost-all-dev
      - sudo apt install -y graphviz

    build_script:
      - cmake -D Qt5_DIR=$HOME/Qt/5.14.2/gcc_64/lib/cmake/Qt5 ..
      - cmake --build .

before_build:
  - mkdir build
  - cd build