language: cpp

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - qt5-default

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .